filter {
  if [deviceVendor] =~ /(?i)palo alto/ {
    mutate { add_tag => ["palo_alto"] }
  } else if [deviceVendor] =~ /(?i)forcepoint/ {
    mutate { add_tag => ["forcepoint"] }
  } else if [deviceVendor] =~ /(?i)imperva/ {
    mutate { add_tag => ["imperva"] }
  } else if [deviceVendor] =~ /(?i)(thycotic|delinea)/ {
    mutate { add_tag => ["thycotic"] }
  } else if [deviceVendor] =~ /(?i)manageengine/ {
    mutate { add_tag => ["manageengine"] }
  }
}
