filter {
  if "imperva" in [tags] {
    # Imperva unix timestamp kullanır
    if [deviceCustomDate1] {
      date {
        match   => ["deviceCustomDate1", "UNIX", "UNIX_MS", "ISO8601"]
        target  => "@timestamp"
        timezone => "UTC"
      }
    }
  }
}
