filter {
  if "manageengine" in [tags] {
    # rt = UNIX_MS timestamp (05_repair'da receiptTime olarak rename edildi)
    if [receiptTime] {
      date {
        match   => ["receiptTime", "UNIX_MS", "UNIX"]
        target  => "@timestamp"
        timezone => "UTC"
      }
    }

    # filePath non-standard → RequestURL
    if [filePath] and ![requestUrl] {
      mutate { rename => { "filePath" => "requestUrl" } }
    }
  }
}
