filter {
  if "thycotic" in [tags] {
    # rt alanını @timestamp olarak kullan
    if [receiptTime] {
      date {
        match   => ["receiptTime", "MMM dd yyyy HH:mm:ss", "MMM  d yyyy HH:mm:ss", "ISO8601"]
        target  => "@timestamp"
        timezone => "UTC"
      }
    }
  }
}
