filter {
  mutate {
    rename => {
      "deviceVendor"        => "DeviceVendor"
      "deviceProduct"       => "DeviceProduct"
      "deviceVersion"       => "DeviceVersion"
      "signatureId"         => "DeviceEventClassID"
      "name"                => "Activity"
      "severity"            => "LogSeverity"
      "sourceAddress"       => "SourceIP"
      "destinationAddress"  => "DestinationIP"
      "sourcePort"          => "SourcePort"
      "destinationPort"     => "DestinationPort"
      "transportProtocol"   => "Protocol"
      "deviceAction"        => "DeviceAction"
      "applicationProtocol" => "ApplicationProtocol"
      "deviceEventCategory" => "DeviceEventCategory"
      "requestUrl"          => "RequestURL"
      "requestMethod"       => "RequestMethod"
      "sourceUserId"        => "SourceUserID"
      "sourceUserName"      => "SourceUserName"
      "destinationUserName" => "DestinationUserName"
      "message"             => "Message"
      "fileName"            => "FileName"
      "sourceHostName"      => "SourceHostName"
      "destinationHostName" => "DestinationHostName"
      "deviceCustomString1" => "DeviceCustomString1"
      "deviceCustomString2" => "DeviceCustomString2"
      "deviceCustomString3" => "DeviceCustomString3"
      "deviceCustomString4" => "DeviceCustomString4"
      "deviceCustomString5" => "DeviceCustomString5"
      "deviceCustomString6" => "DeviceCustomString6"
      "deviceCustomDate1"   => "DeviceCustomDate1"
      "flexString1"         => "FlexString1"
      "flexString2"         => "FlexString2"
    }
    convert      => { "SourcePort" => "integer" "DestinationPort" => "integer" }
    remove_field => [
      "host", "syslog_pri", "syslog_facility_code", "syslog_severity_code",
      "deviceCustomString1Label", "deviceCustomString2Label", "deviceCustomString3Label",
      "deviceCustomString4Label", "deviceCustomString5Label", "deviceCustomString6Label",
      "deviceCustomDate1Label"
    ]
  }
}
